Repository hyonun321/toss_copy, pull requests merged in 2025-03, with the labels that each got.

#17 Feature 레이아웃과 폴더구조 생성
  client/public/file.svg
  client/public/globe.svg
  client/public/images/storage.png
  client/public/images/wallet.png
  client/public/next.svg
  client/public/vercel.svg
  client/public/window.svg
  client/src/app/components/Button.tsx
  client/src/app/components/Footer.tsx
  client/src/app/components/Header.tsx
  client/src/app/components/ImageTextContainer.tsx
  client/src/app/components/ResponsiveWrapper.tsx
  client/src/app/favicon.ico
  client/src/app/home/page.tsx
  client/src/app/hooks/useWindowSize.ts
  client/src/app/layout.tsx
  client/src/app/main/page.module.css
  client/src/app/main/page.tsx
  client/src/app/mypage/page.tsx
  client/src/app/page.tsx
  client/src/app/search/page.tsx
  client/src/app/setting/page.tsx
Labels: ✨ Feature, FE

#19 Feature 메인뷰 unlogined 구현
  client/next.config.ts
  client/package.json
  client/public/images/doss_logo.png
  client/src/app/components/Button.tsx
  client/src/app/components/Button/Button.style.ts
  client/src/app/components/Button/Button.tsx
  client/src/app/components/ClientGlobalStyles.tsx
  client/src/app/components/Footer.tsx
  client/src/app/components/Header.tsx
  client/src/app/components/ImageText/ImageText.style.ts
  client/src/app/components/ImageText/ImageText.tsx
  client/src/app/components/ImageTextContainer.tsx
  client/src/app/components/viewContainer/viewContainer.tsx
  client/src/app/home/page.tsx
  client/src/app/layout.tsx
  client/src/app/main/page.tsx
  client/src/app/mypage/page.tsx
  client/src/app/page.tsx
  client/src/app/search/page.tsx
  client/src/app/setting/page.tsx
  client/src/app/theme/fonts.ts
  client/src/app/theme/global.ts
  client/src/app/theme/theme.ts
  client/tsconfig.json
  client/yarn.lock
Labels: FE, 🎨Design

#20 Feature 로그인db 구현
  server/.gitignore
  server/pom.xml
  server/src/main/java/com/shop/cafe/Project1CafeApplication.java
  server/src/main/java/com/shop/cafe/controller/CartController.java
  server/src/main/java/com/shop/cafe/controller/MemberController.java
  server/src/main/java/com/shop/cafe/controller/ProductController.java
  server/src/main/java/com/shop/cafe/dao/CartDao.java
  server/src/main/java/com/shop/cafe/dao/LoginDao.java
  server/src/main/java/com/shop/cafe/dao/MemberDao.java
  server/src/main/java/com/shop/cafe/dao/ProductDao.java
  server/src/main/java/com/shop/cafe/dao/SaltDao.java
  server/src/main/java/com/shop/cafe/dto/Cart.java
  server/src/main/java/com/shop/cafe/dto/Login.java
  server/src/main/java/com/shop/cafe/dto/Member.java
  server/src/main/java/com/shop/cafe/dto/SaltInfo.java
  server/src/main/java/com/shop/cafe/service/CartService.java
  server/src/main/java/com/shop/cafe/service/MemberService.java
  server/src/main/java/com/shop/cafe/service/ProductService.java
  server/src/main/java/com/shop/cafe/util/JwtTokenProvider.java
  server/src/main/java/com/shop/cafe/util/OpenCrypt.java
  server/src/main/resources/application.properties
  server/src/main/resources/mapper/cart.xml
  server/src/main/resources/mapper/login.xml
  server/src/main/resources/mapper/salt.xml
Labels: Build, BE

#22 Feature 메인 로그인/회원가입 구현
  client/package.json
  client/public/images/Left_Actionable.png
  client/src/app/components/AuthHeader/AuthHeader.module.css
  client/src/app/components/AuthHeader/AuthHeader.tsx
  client/src/app/components/Buttonv2/Button2.style.ts
  client/src/app/components/Buttonv2/Buttonv2.tsx
  client/src/app/components/TextField/InputField.module.css
  client/src/app/components/TextField/InputField.tsx
  client/src/app/components/Title/Title.module.css
  client/src/app/components/Title/Title.tsx
  client/src/app/hooks/useLogin.ts
  client/src/app/hooks/useValidation.ts
  client/src/app/login/page.module.css
  client/src/app/login/page.tsx
  client/src/app/loginbegin/page.module.css
  client/src/app/loginbegin/page.tsx
  client/src/app/register/context.tsx
  client/src/app/register/funnelcontext.tsx
  client/src/app/register/page.module.css
  client/src/app/register/page.tsx
  client/src/app/register/registerview.tsx
  client/yarn.lock
Labels: ✨ Feature, FE, 🎨Design

#21 Feature 메인뷰 logined 구현
  client/package.json
  client/public/images/egg.png
  client/src/app/components/BottomNavigation/BottomNavigation.style.ts
  client/src/app/components/BottomNavigation/BottomNavigation.tsx
  client/src/app/components/CategoryTabs/CategoryTabs.style.ts
  client/src/app/components/CategoryTabs/CategoryTabs.tsx
  client/src/app/components/HomeView/HomeView.style.ts
  client/src/app/components/HomeView/HomeView.tsx
  client/src/app/components/MainView/MainView.module.css
  client/src/app/components/MainView/MainView.tsx
  client/src/app/components/MarketHeader/MarketHeader.style.ts
  client/src/app/components/MarketHeader/MarketHeader.tsx
  client/src/app/components/StockListItem/StockListItem.style.ts
  client/src/app/components/StockListItem/StockListItem.tsx
  client/src/app/globals.css
  client/src/app/home/page.tsx
  client/src/app/layout.tsx
  client/src/app/main/page.tsx
  client/src/app/page.tsx
  client/src/app/theme/global.ts
  client/src/app/theme/theme.ts
  client/tsconfig.json
  client/yarn.lock
Labels: ✨ Feature, 🚀refactor, FE, 🎨Design

#24 Feature router 연동
  client/src/app/components/AuthHeader/AuthHeader.module.css
  client/src/app/components/BottomNavigation/BottomNavigation.tsx
  client/src/app/components/MainView/MainView.tsx
  client/src/app/components/MarketHeader/MarketHeader.tsx
  client/src/app/components/SearchBar/SearchBar.tsx
  client/src/app/components/TextField/InputField.module.css
  client/src/app/components/Title/Title.module.css
  client/src/app/login/page.module.css
  client/src/app/login/page.tsx
  client/src/app/loginbegin/page.module.css
  client/src/app/loginbegin/page.tsx
  client/src/app/page.tsx
  client/src/app/register/page.module.css
Labels: FE

#26 Feature 메인 로그인 구현(회원가입 완료 페이지 구현)
  client/package.json
  client/public/images/phone.png
  client/public/images/smile.png
  client/src/app/onboarding/page.module.css
  client/src/app/onboarding/page.tsx
  client/yarn.lock
Labels: ✨ Feature, FE, 🎨Design

#25 Feature 국내주식정보 db연동
  client/package.json
  client/public/images/loading.gif
  client/src/app/components/CategoryTabs/CategoryTabs.tsx
  client/src/app/components/HomeView/HomeView.style.ts
  client/src/app/components/HomeView/HomeView.tsx
  client/src/app/components/MarketHeader/MarketHeader.tsx
  client/src/app/constants/tabMappings.ts
  client/src/app/hooks/useStockData.js
  client/src/app/stockApi.js
  client/src/app/types/index.ts
  client/src/app/utils/formatters.ts
  client/tsconfig.json
  client/yarn.lock
  server/.gitignore
  server/pom.xml
  server/src/main/java/com/shop/cafe/controller/StockController.java
  server/src/main/java/com/shop/cafe/dao/StockDao.java
  server/src/main/java/com/shop/cafe/dto/StockApiResponse.java
  server/src/main/java/com/shop/cafe/dto/StockInfo.java
  server/src/main/java/com/shop/cafe/service/StockApiService.java
  server/src/main/java/com/shop/cafe/service/StockService.java
  server/src/main/resources/application.properties
Labels: ✨ Feature, BE

#27 Feature 로그인 회원가입 be연동
  client/src/app/components/HomeView/HomeView.tsx
  client/src/app/components/MarketHeader/MarketHeader.tsx
  client/src/app/hooks/useLogin.ts
  client/src/app/hooks/useSignup.ts
  client/src/app/hooks/useValidation.ts
  client/src/app/login/page.tsx
  client/src/app/onboarding/page.module.css
  client/src/app/onboarding/page.tsx
  client/src/app/page.tsx
  client/src/app/register/page.tsx
  client/src/app/register/registerview.tsx
  client/src/app/utils/auth.ts
  client/src/app/utils/validation.ts
  server/src/main/java/com/shop/cafe/dao/MemberDao.java
  server/src/main/resources/mapper/login.xml
Labels: ✨ Feature, FE, BE

#28 Feature 주식검색기능 구현
  client/src/app/components/HomeView/HomeView.tsx
  client/src/app/components/PopularStocks/PopularStocks.style.ts
  client/src/app/components/PopularStocks/PopularStocks.tsx
  client/src/app/components/SearchBar/SearchBar.style.ts
  client/src/app/components/SearchBar/SearchBar.tsx
  client/src/app/components/SearchTags/SearchTags.style.ts
  client/src/app/components/SearchTags/SearchTags.tsx
  client/src/app/components/SearchView/SearchView.tsx
  client/src/app/components/SearchView/stockApi.ts
  client/src/app/components/SkeletonSearchTags/SkeletonSearchTags.style.ts
  client/src/app/components/SkeletonSearchTags/SkeletonSearchTags.tsx
  client/src/app/components/searchResults/SearchResults.style.ts
  client/src/app/components/searchResults/SearchResults.tsx
  client/src/app/data/dummyStocks.ts
  client/src/app/types/stock.ts
  server/pom.xml
  server/src/main/java/com/shop/cafe/controller/StockController.java
  server/src/main/java/com/shop/cafe/controller/StockHistoryController.java
  server/src/main/java/com/shop/cafe/controller/StockSearchController.java
  server/src/main/java/com/shop/cafe/dao/SearchHistoryDao.java
  server/src/main/java/com/shop/cafe/dao/StockSearchRepository.java
  server/src/main/java/com/shop/cafe/dto/SearchHistoryDto.java
  server/src/main/java/com/shop/cafe/dto/StockDocument.java
  server/src/main/java/com/shop/cafe/service/SearchHistoryService.java
  server/src/main/java/com/shop/cafe/service/StockApiService.java
  server/src/main/java/com/shop/cafe/service/StockIndexService.java
  server/src/main/java/com/shop/cafe/service/StockService.java
  server/src/main/resources/application.properties
  stock-loader/.gitignore
  stock-loader/check.js
  stock-loader/loading.js
  stock-loader/package.json
  stock-loader/stocks.csv
  stock-loader/yarn.lock
Labels: ✨ Feature, FE, BE

#37 Feature 마이페이지 찜하기연동
  client/src/app/(protected)/home/HomeView/HomeView.tsx
  client/src/app/(protected)/mypage/MyPageView.tsx
  client/src/app/components/BottomSheet/BottomSheetContent.tsx
  client/src/app/components/StockListItem/StockListItem.tsx
  client/src/app/stores/authStore.ts
  client/src/app/types/index.ts
  client/src/app/utils/formatters.ts
  server/src/main/java/com/shop/cafe/controller/LikeController.java
  server/src/main/java/com/shop/cafe/controller/MemberController.java
  server/src/main/java/com/shop/cafe/controller/StockHistoryController.java
  server/src/main/java/com/shop/cafe/controller/StockSearchController.java
  server/src/main/java/com/shop/cafe/dao/LikeDao.java
  server/src/main/java/com/shop/cafe/dto/Like.java
  server/src/main/java/com/shop/cafe/service/LikeService.java
  server/src/main/java/com/shop/cafe/service/StockApiService.java
  server/src/main/java/com/shop/cafe/service/StockService.java
Labels: ✨ Feature, FE, BE

#40 Feature 주식 검색 찜하기 구현
  client/src/app/(protected)/home/HomeView/HomeView.tsx
  client/src/app/(protected)/mypage/MyPageView.tsx
  client/src/app/(protected)/search/SearchView/SearchView.tsx
  client/src/app/components/StockListItem/StockListItem.tsx
  client/src/app/types/index.ts
  client/src/app/types/stock.ts
  client/src/app/utils/formatters.ts
  server/src/main/java/com/shop/cafe/controller/LikeController.java
  server/src/main/java/com/shop/cafe/dao/LikeDao.java
  server/src/main/java/com/shop/cafe/dao/StockDao.java
  server/src/main/java/com/shop/cafe/dto/Like.java
  server/src/main/java/com/shop/cafe/dto/StockCodeName.java
  server/src/main/java/com/shop/cafe/service/StockApiService.java
  server/src/main/java/com/shop/cafe/service/StockService.java
Labels: ✨ Feature, FE, BE

#42 Feature 나스닥 정보 홈뷰 생성
  client/src/app/(protected)/home/HomeView.style.ts
  client/src/app/(protected)/home/HomeView.tsx
  client/src/app/(protected)/home/page.tsx
  client/src/app/(protected)/mypage/MyPageView.tsx
  client/src/app/components/MarketHeader/MarketHeader.style.ts
  client/src/app/components/MarketHeader/MarketHeader.tsx
  client/src/app/components/MarketToggle/MarketToggle.style.ts
  client/src/app/components/MarketToggle/MarketToggle.tsx
  client/src/app/components/StockListItem/StockListItem.style.ts
  client/src/app/components/StockListItem/StockListItem.tsx
  client/src/app/types/index.ts
  client/src/app/utils/formatters.ts
  server/src/main/java/com/shop/cafe/controller/CartController.java
  server/src/main/java/com/shop/cafe/controller/MemberController.java
  server/src/main/java/com/shop/cafe/controller/StockController.java
  server/src/main/java/com/shop/cafe/controller/StockSearchController.java
  server/src/main/java/com/shop/cafe/dao/MemberDao.java
  server/src/main/java/com/shop/cafe/dao/StockDao.java
  server/src/main/java/com/shop/cafe/dto/IndexApiResponse.java
  server/src/main/java/com/shop/cafe/dto/IndexInfo.java
  server/src/main/java/com/shop/cafe/dto/StockInfo.java
  server/src/main/java/com/shop/cafe/service/MemberService.java
  server/src/main/java/com/shop/cafe/service/StockApiService.java
  server/src/main/java/com/shop/cafe/service/StockService.java
  server/src/main/java/com/shop/cafe/util/JwtTokenProvider.java
  server/src/main/java/com/shop/cafe/util/OpenCrypt.java
Labels: ✨ Feature, 🚀refactor, FE, 🎨Design, BE

#44 Feature 완성도 ux 개선
  client/src/app/(protected)/mypage/MyPageView.tsx
  client/src/app/(protected)/search/SearchView/SearchView.tsx
  client/src/app/(protected)/setting/page.tsx
  client/src/app/(public)/register/page.tsx
  client/src/app/components/MarketHeader/MarketHeader.tsx
  server/src/main/java/com/shop/cafe/service/StockApiService.java
Labels: 🚀refactor
